import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import './globals.css';

const poppinsSans = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});



export const metadata: Metadata = {
  title: 'DesignAgency',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${poppinsSans.variable}  antialiased`}>{children}</body>
    </html>
  );
}
